### ISSUE TITLE
Complete DisseminationPlan sections

### ISSUE THREAD

**Issue by mrostren** [ModelWriter/WP7#7]
The concerned Deliverable file plan is already shared on google drive.

This issue must be Assigned to all partners !

**Comment by mrostren** [comment]
We need your contribution so please add your additional actions, complete or comment the existing.
You find the list of actions and the dissemination plan report on google drive in the WP7 repository: https://drive.google.com/?usp=folder&authuser=0#folders/0B115qHHFY_rua2NQOFVHREx0RlU
"D7.1.1-DisseminationPlan" and "D7.1.1-DisseminationPlan Actions"

**Comment by annemonceaux** [comment]
Bonjour Marwa,

peux-tu stp m’envoyer le doc dissemination – je n’y accède pas d’ici et je voudrais jeter un dernier coup d’œil pour les contribution Airbus au plan de conf
merci d’avance
Anne
